[project]
name = "emotion-and-sentiment-recognition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "gensim>=4.3.3",
    "huggingface-hub>=0.31.4",
    "nltk>=3.9.1",
    "numpy>=1.26.4",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "scipy>=1.13.1",
    "tensorflow>=2.16.2",
    "tensorflow-macos>=2.16.2",
    "tensorflow-metal>=1.2.0",
    "torch>=2.7.0",
    "tqdm>=4.67.1",
    "transformers>=4.52.2",
]
